### ISSUE TITLE
Navigate the map with history

### ISSUE THREAD

**Issue by steveoh** [agrc/wri#14]
Place a forward and backward component on the mapping interface that allows a user to backup their navigation history with the option to reset to initial.

### Tasks

- [x] UI to move forward and backward through navigation history
- [x] UI to reset to the initial view

### Improvement

- [x] Add a treatment to the UI to visually show a viewer that there are no more states to navigate through

### Prior implementation

![Image](https://github.com/user-attachments/assets/d009e474-590f-43fe-adee-35b7289a0b6e)

#### References

- #15
