### ISSUE TITLE
Display project features and information based on url

### ISSUE THREAD

**Issue by steveoh** [agrc/wri#16]
WRI projects are linked to by hash routing from the parent application using an `id=project_id` pattern e.g. `/map/map.html#id=2427.

### Tasks

1. When the app loads check for a project hash

   - [x] Query for the project information and display the project information panel
   - [x] Zoom to the project features extent

1. When a project centroid or project features are clicked and no project is already selected

   - [x] Query for the project information and display the project information panel
   - [x] Zoom to the project features extent

1. When the hash changes (typically by a user interaction)

   - [x] Query for the project information and display the project information panel
   - [x] Zoom to the project features extent

#### References

- #19
