### ISSUE TITLE
Display project and feature information

### ISSUE THREAD

**Issue by steveoh** [agrc/wri#17]
Create a project information component to display specific project information.

### Tasks

- [ ] A component that is mobile friendly to display project information
- [ ] Has UI to be hidden/collapsed when not needed
- [ ] Shows project features with attributes and opacity controls
- [ ] Has a link back to the parent app e.g. (https://wri.utah.gov/wri/project/title.html?id=project_id)
- [ ] When logged in possibly display feature creation controls
- [ ] Possibly contains reference data controls
- [ ] Possibly contains adjacent data controls

### Project details UI

- [ ] The project title
- [ ] The project status
- [ ] The project description
- [ ] The project manager
- [ ] The project leading agency
- [ ] The project region

The intersected project information for 

- [ ] land ownership by owner admin acres
- [ ] affected county acres
- [ ] affected terrestrial acres
- [ ] affected aquatic/riparian acres
- [ ] affected stream miles
- [ ] affected easement/acquisition acres
- [ ] affected sage grouse acres

### Prior implementation

![Image](https://github.com/user-attachments/assets/0561b5d2-1208-45ad-ab60-8be331ee582f)

### Project features UI

- [ ] Display a list of features associated with the project and their attributes
- [ ] Highlight and zoom to the feature when it's row is clicked
- [ ] Allow the opacity of the feature to be modified

### Prior implementation

![Image](https://github.com/user-attachments/assets/567ce411-dacb-4fb8-8e4d-5e96e8ea0ea3)

### Specific project feature details UI

When a feature is selected display more information about it

- [ ] The feature type as Category
- [ ] The feature action
- [ ] The feature treatment and herbicide if applicable
- [ ] Denote if it is a re-treatment
- [ ] The feature size in ac if polygon

The intersected feature information for 

- [ ] land ownership by owner admin acres
- [ ] affected county acres
- [ ] affected terrestrial acres
- [ ] affected aquatic/riparian acres
- [ ] affected stream miles
- [ ] affected easement/acquisition acres
- [ ] affected sage grouse acres

### Prior implementation

![Image](https://github.com/user-attachments/assets/8fdbb991-5e4d-42cd-8e84-1fd0b9c61e06)

If logged in and authorized display UI to

- [ ] Modify or delete the feature

### Prior implementation

![Image](https://github.com/user-attachments/assets/4faba5a7-6c04-4928-92a4-f9f7b326cfb9)
