### ISSUE TITLE
Toggle between project centroids and geometries

### ISSUE THREAD

**Issue by steveoh** [agrc/wri#2]
Allow the map data to initially draw quickly by showing centroids yet allow the fine grain project data to be available

### Tasks

- [x] Place a mobile friendly toggle component on the mapping interface that swaps project centroids for actual project geometries
- [x] If the map zoom level is below 13 (cities, metropolitan area level), show the button and centroids.
- [x] If the map is zoomed to 13 or higher (city, town level) hide the button and show the project features.

### Improvements

- [x] It could be an improvement to instead of hiding the button, continue to allow the features to be swapped. 

### Reference

[Zoom level to scale converter tool](https://developers.arcgis.com/documentation/mapping-and-location-services/reference/zoom-levels-and-scale/#conversion-tool)

### Prior implementation

![Image](https://github.com/user-attachments/assets/c43628c1-8a4e-4da7-bef2-75f18bd5a069)

#### References

- #15
