### ISSUE TITLE
Create and modify project feature geometries

### ISSUE THREAD

**Issue by steveoh** [agrc/wri#20]
When projects move between their status's features need to be created and updated to match reality. Using the latest ArcGIS Map SDK for JavaScript improve the creation and editing workflow.

### Tasks

- [ ] Allow drawing multipoint, polyline, and polygon features depending on the feature type
- [ ] Allow cutting lines and polygon into multiple parts
- [ ] Allow vertex dragging of polygons and polylines and moving of multi points
- [ ] Allow snapping to other project features including visible adjacent project features
- [ ] Allow snapping to land ownership* 
- [ ] Feature of the same type cannot overlap

*Vector tiles are not supported by snapping.

#### References

- #8 
- #15
