### ISSUE TITLE
Toggle project types

### ISSUE THREAD

**Issue by steveoh** [agrc/wri#21]
Allow map viewers to filter project features by status to help find information they need by removing unnecessary data

### Tasks

- [ ] Place a mobile friendly component on the mapping interface that allows the user to toggle by project status.
- [ ] The toggle components should match the project status colors to act as a legend
- [ ] Hide and how features based on the active toggle behavior
- [ ] The filter shows the filtered data for project centroids and project features
- [ ] The filtering always uses a `any | or` join since projects can't have more than one status
- [ ] Allow the filter to be reset to the default where all feature types are displayed

### Prior implementation

![Image](https://github.com/user-attachments/assets/22d71108-a10f-4869-af2b-9bcdff64bbdf)

#### References

- #15
