### ISSUE TITLE
Toggle project feature types

### ISSUE THREAD

**Issue by steveoh** [agrc/wri#4]
Allow map viewers to filter project features by type to help find information they need by removing unnecessary data

### Tasks

- [x] Place a mobile friendly component on the mapping interface that allows the user to toggle feature types.
- [x] Allow the filter to be reset to the default where all feature types are displayed
- [x] Allow building the filter with `any | or` or `all | and` joins
- [x] Hide and how features based on the active toggle behavior
- [x] The filter shows the filtered data for project centroids and project features

### Prior implementation

![Image](https://github.com/user-attachments/assets/8fd9366f-984e-44fc-b96c-a10549506f67)

#### References

- #15

**Comment by stdavis** [comment]
I think that the project status filter could be added to this issue.
