### ISSUE TITLE
Create new features

### ISSUE THREAD

**Issue by steveoh** [agrc/wri#6]
When a user is logged in and viewing a project they are able to edit, with an editable status, and the project allows features

### Tasks

- [x] Place some UI to allow adding features in the project information panel. 
- [x] The shape and all inputs are required before sending the request to the API. #19 
- [x] The editor should be allowed to pick from the available feature types
   <details>
     <summary>Feature types currently come from an api call (/api/supporting/filters)</summary>
   
     ```json
    "featureType": [
        {
            "code": 1,
            "featureType": "Terrestrial Treatment Area",
            "type": "Poly "
        },
        {
            "code": 2,
            "featureType": "Aquatic/Riparian Treatment Area",
            "type": "Poly "
        },
        {
            "code": 3,
            "featureType": "Affected Area",
            "type": "Poly "
        },
        {
            "code": 4,
            "featureType": "Easement/Acquisition",
            "type": "Poly "
        },
        {
            "code": 5,
            "featureType": "Guzzler",
            "type": "Point"
        },
        {
            "code": 8,
            "featureType": "Other point feature",
            "type": "Point"
        },
        {
            "code": 9,
            "featureType": "Fish passage structure",
            "type": "Point"
        },
        {
            "code": 10,
            "featureType": "Fence",
            "type": "Line "
        },
        {
            "code": 11,
            "featureType": "Pipeline",
            "type": "Line "
        },
        {
            "code": 12,
            "featureType": "Dam",
            "type": "Line "
        },
        {
            "code": 13,
            "featureType": "Water development point feature",
            "type": "Point"
        }
   ```
   </details>

- [x] Aquatic and Terrestrial treatment types (code 1 and 2) are able to add multiple action and treatment combinations and to denote if it is a re-treatment.
- [x] If a herbicide action is selected, an additional herbicide dropdown choice is required
- [x] The additional actions are able to be edited and removed

The shape drawing and shapefile uploading are defined in separate issues

### Improvements

- [x] Add a drop down with the following values
   - Cultural Resource Inventory
   - Biological Surveys
   - Engineering 
   - Other
~- [ ] If other is selected, provide a freeform text input. Use the same max length as the other point feature type.~

### Prior implementation

![Image](https://github.com/user-attachments/assets/cb4e0a27-3d2a-4a4a-88e2-6521d8eb1718)
![Image](https://github.com/user-attachments/assets/129708c0-6562-46bb-8c1f-66b836751909)

#### References

- #15 
- #17 
- #19

**Comment by stdavis** [comment]
@chriswnek I need more specifics on the "Add a drop down with the following values" enhancement above:
- [x] Is this for every feature type? 
- [x] Where should the values from this new dropdown be stored in the database?

**Comment by chriswnek** [comment]
Additional info based on meeting held on 4/8/26:

- When adding a new feature and selecting "Affected area", an action dropdown with four options will be added.
- Selecting "Other" will no longer need to trigger a text box.  It will just remain as an option in the dropdown.
- The AREAACTION table stores the "Affected Area" and the "Type".  ActionDescription is where the dropdown values will be stored.
