### ISSUE TITLE
Toggle reference layer visibility

### ISSUE THREAD

**Issue by steveoh** [agrc/wri#9]
Place a reference data visibility toggle component on the mapping interface that is also visible in the project pane when viewing a specific project. Some layers need a treatment to show the legend to help viewers understand the layers symbology meaning.

### Tasks

- [x] Place the component in the default map view
- [ ] Place the component in the project information component
- [x] Allow reference data to be turned on and off
- [x] Allow labels to be turned on and off
- [x] Show legend swatches
- [x] Configure popups

### Participating reference data

- [x] [Land ownership](https://gis.trustlands.utah.gov/hosting/rest/services/Hosted/Land_Ownership_WM_VectorTile/VectorTileServer) (with a legend)
- [x] [UWRI regions](https://wrimaps.utah.gov/arcgis/rest/services/WRI/Reference/MapServer/5)
- [x] [BLM Districts](https://wrimaps.utah.gov/arcgis/rest/services/WRI/Reference/MapServer/0)
- [x] [Forest Service](https://wrimaps.utah.gov/arcgis/rest/services/WRI/Reference/MapServer/1)
- [x] [Sage grouse areas](https://wrimaps.utah.gov/arcgis/rest/services/WRI/Reference/MapServer/4)
- [x] [PLSS Sections](https://wrimaps.utah.gov/arcgis/rest/services/UtahPLSS/MapServer)*
- [x] [HUC10](https://wrimaps.utah.gov/arcgis/rest/services/WRI/Reference/MapServer/2)*
- [x] [Range trend sites](https://wrimaps.utah.gov/arcgis/rest/services/WRI/Reference/MapServer/7)
- [x] [Fire thread index](https://utwrapcache.timmons.com/mapproxy/wmts/firethreatindex/webmercator/${level}/${col}/${row}.png)
- [x] [NHD Streams](https://wrimaps.utah.gov/arcgis/rest/services/WRI/Reference/MapServer/14)*
- [x] [Average annual precipitation](https://wrimaps.utah.gov/arcgis/rest/services/WRI/Reference/MapServer/15)
- [x] [Shared stewardship priority](ttps://services.arcgis.com/ZzrwjTRez6FJiOq4/arcgis/rest/services/SharedStewardshipPriorityAreas_Public/FeatureServer/0)

### Improvements

1. Currently the map service has extra label layers for these services. We should consider removing the need for those and add labels from one place.
2. Consider using the [UtahPLSS vector tile service](https://tiles.arcgis.com/tiles/99lidPhWCzftIe9K/arcgis/rest/services/UtahPLSS/VectorTileServer) instead of a raster tile base map on the GIS server.
3. Consider using the [Utah Watersheds Area](https://services1.arcgis.com/99lidPhWCzftIe9K/ArcGIS/rest/services/UtahWatershedsArea/FeatureServer/0) AGOL service.
4. Consider using the AGOL [streams_nhd](https://services1.arcgis.com/99lidPhWCzftIe9K/ArcGIS/rest/services/UtahStreamsNHD/FeatureServer/0)
5. Add UI treatment to denote scale dependent rendering

### Prior implementation

![image](https://github.com/user-attachments/assets/791da88b-c6e6-4dfd-9a5b-96db0dfe4de0)
![Image](https://github.com/user-attachments/assets/597ef337-820b-44ce-a539-3ae03b4cd2ff)

#### References

- #15
- #10

**Comment by steveoh** [comment]
Some recommendations,

1. precipitation would draw faster if cached as a vector tile
2. forest service would draw faster if cached as a veetor tile
